Delta: [null, null]
Ec: [null, null]
Ej: [null, null]
Q1: [null, null]
Sum: [null, null]
T1_nopurcell: [null, null]
T1_purcell: [null, null]
Tphi: [null, null]
alpha: [null, null]
g: [chi, chi]
g_chi: [null, null]
g_lamb: [null, null]
kappa_low: [null, null]
ng: [null, null]
nqubits: 2
nreadout: [null, null]
ratio: [null, null]
stats:
  q1_max: [null, null]
  q1_mean: [null, null]
  q1_std: [null, null]
  t1_max: [null, null]
  t1_mean: [null, null]
  t1_std: [null, null]
  t1max_nopurcell: [null, null]
  t1mean_nopurcell: [null, null]
  t2e_max: [null, null]
  t2e_mean: [null, null]
  t2e_std: [null, null]
  t2r_max: [null, null]
  t2r_mean: [null, null]
  t2r_std: [null, null]
  tphi_max: [null, null]
  tphi_mean: [null, null]
  tphi_std: [null, null]
