Delta: [857.0536, -307.3647, 709.0441]
Ec: [0.1213, 0.1785, 0.1785]
Ej: [22.9778, 12.2781, 12.2781]
Q1: [0.7967, 1.2566, 1.2566]
Sum: [10052.3696, 12266.0237, 12709.0441]
T1_nopurcell: [56.3893, null, null]
T1_purcell: [51.985, 3.6273, null]
Tphi: [11.9321, .inf, .inf]
alpha: [-129.2798, -200, -200]
g: [lamb, lamb, chi]
g_chi: [208.1003, -0.0, -0.0]
g_lamb: [71.5156, 70.8966, 111.3281]
kappa_low: [0.4397, 0.8247, 0.3086]
ng: [35.905, 4.6989, null]
nqubits: 3
nreadout: [null, null, null]
ratio: [189.4069, 68.7895, 68.7895]
stats:
  q1_max: [null, null, null]
  q1_mean: [null, null, null]
  q1_std: [null, null, null]
  t1_max: [null, null, null]
  t1_mean: [null, null, null]
  t1_std: [null, null, null]
  t1max_nopurcell: [null, null, null]
  t1mean_nopurcell: [null, null, null]
  t2e_max: [null, null, null]
  t2e_mean: [null, null, null]
  t2e_std: [null, null, null]
  t2r_max: [null, null, null]
  t2r_mean: [null, null, null]
  t2r_std: [null, null, null]
  tphi_max: [null, null, null]
  tphi_mean: [null, null, null]
  tphi_std: [null, null, null]
