aliases: {ip: 192.168.137.1, soc: smpd_qick}
device:
  qubit:
    T1: [24.91, 22.78]
    T2e: [23.84, 35.2]
    T2r: [64.7, 6.4]
    f_ef: [4130.8845, 4131.1478]
    f_ge: [4378.5871, 4378.5474]
    kappa: [0.1511, 0]
    low_gain: 0.002
    max_gain: 1
    pop: [0, 0.0022]
    pulses:
      pi_ef:
        gain: [0.0151, 0.2209]
        phase: [0, 0]
        sigma: [0.05, 0.025]
        sigma_inc: [5, 5]
        type: [gauss, gauss]
      pi_ge:
        gain: [0.1398, 0.1175]
        phase: [0, 0]
        sigma: [0.05, 0.06]
        sigma_inc: [5, 4]
        type: [gauss, gauss]
    spec_gain: [1, 1]
    temp: [0, 34.333]
    tuned_up: [true, true]
  readout:
    active_reset: [false, false]
    chi: [-1.5516, -7.3967]
    fidelity: [0.2646, 0.7162]
    final_delay: [149.49, 136.69]
    frequency: [6917.1348, 7741.7305]
    gain: [0.01, 0.01]
    kappa: [0.2211, 1.9165]
    lamb: [-4.6108, -24.2306]
    max_gain: 1
    nstark: [102817.8044, null]
    phase: [55.4165, 113.8695]
    qe: [5.4258, 0.4607]
    qi: [7.3923, 3.2795]
    readout_length: [7.623, 8.9327]
    reps: [1, 1.7944]
    reps_base: 150
    rescale: [false, false]
    reset: [3, 3]
    rounds: [1, 1]
    rounds_base: 1
    sigma: [1.7775, 1.9399]
    threshold: [0.1059, -0.5202]
    tm: [0.5526, 0.4419]
    trig_offset: [0.5241, 0.53]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 1]
        type: [dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1]
        nyquist: [1, 1]
        type: [full, full]
      readout:
        ch: [0, 2]
        nyquist: [2, 2]
        type: [full, full]
