Delta: [2539.1726, 3363.4581]
Ec: [0.2173, 0.2118]
Ej: [12.2096, 12.497]
Q1: [0.546, 0.4812]
Sum: [11295.4042, 12120.6047]
T1_nopurcell: [23.4306, -73.0532]
T1_purcell: [129.8926, 14.1115]
Tphi: [18.8472, 18.2663]
alpha: [-247.2313, -240.0073]
g: [chi, lamb]
g_chi: [144.1844, 322.4281]
g_lamb: [97.7692, 252.5776]
kappa_low: [0.38, 2]
ng: [77.5332, 44.3325]
nqubits: 2
nreadout: [null, null]
ratio: [56.1846, 59.0056]
stats:
  q1_max: [null, null]
  q1_mean: [null, null]
  q1_std: [null, null]
  t1_max: [null, null]
  t1_mean: [null, null]
  t1_std: [null, null]
  t1max_nopurcell: [null, null]
  t1mean_nopurcell: [null, null]
  t2e_max: [null, null]
  t2e_mean: [null, null]
  t2e_std: [null, null]
  t2r_max: [null, null]
  t2r_mean: [null, null]
  t2r_std: [null, null]
  tphi_max: [null, null]
  tphi_mean: [null, null]
  tphi_std: [null, null]
