Delta: [1851.1321, 2989.4573, 3735.8635, 3000]
Ec: [0.3523, 0.2315, 0.0064, 0.1785]
Ej: [9.8178, 10.2123, 281.5146, 12.2781]
Q1: [0.6634, 0.5455, 0.1432, 1.2566]
Sum: [11609.8029, 11195.9529, 11334.9695, 11000]
T1_nopurcell: [23.6787, 22.0948, -0.947, null]
T1_purcell: [251.3418, 500.1374, 0.8179, null]
Tphi: [100.92, .inf, .inf, .inf]
alpha: [-443.9173, -269.43, 0.447, -200]
g: [chi, chi, chi, chi]
g_chi: [97.5974, 70.1021, 2472.0336, -0.0]
g_lamb: [66.2806, 59.2864, 114.1533, 0.0]
kappa_low: [0.2457, 0.5702, 0.3713, null]
ng: [89.937, 454.6348, 0.571, null]
nqubits: 4
ratio: [27.8671, 44.1066, 43785.5149, 68.7895]
stats:
  q1_max: [null, null, null, null]
  q1_mean: [null, null, null, null]
  q1_std: [null, null, null, null]
  t1_max: [null, null, null, null]
  t1_mean: [null, null, null, null]
  t1_std: [null, null, null, null]
  t1max_nopurcell: [null, null, null, null]
  t1mean_nopurcell: [null, null, null, null]
  t2e_max: [null, null, null, null]
  t2e_mean: [null, null, null, null]
  t2e_std: [null, null, null, null]
  t2r_max: [null, null, null, null]
  t2r_mean: [null, null, null, null]
  t2r_std: [null, null, null, null]
  tphi_max: [null, null, null, null]
  tphi_mean: [null, null, null, null]
  tphi_std: [null, null, null, null]
