aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [21.64, 21.16, 6, 50]
    T2e: [30.29, 100, 100, 100]
    T2r: [26.15, 12.81, 0.589, 50]
    f_ef: [4435.4181, 3833.8178, 3800, 3800]
    f_ge: [4879.3354, 4103.2478, 3799.553, 4000]
    kappa: [2.3828, -0.0839, 3.0666, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0133, 0.0057, 0, 0]
    pulses:
      pi_ef:
        gain: [0.5168, 0.3047, 0.15, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.04, 0.05, 0.1, 0.1]
        sigma_inc: [4, 4, 5, 5]
        type: [gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.4603, 0.4978, 0.3094, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.035, 0.05, 0.05, 0.1]
        sigma_inc: [5, 4, 5, 5]
        type: [gauss, gauss, gauss, gauss]
    spec_gain: [4, 2, 1, 1]
    temp: [54.2449, 38.088, 0, 0]
    tuned_up: [true, true, false, false]
  readout:
    active_reset: [false, false, false, false]
    chi: [-1.1318, 0, 0, 0]
    fidelity: [0.3367, 0.3436, 0.0059, 0]
    final_delay: [129.86, 126.95, 80, 300]
    frequency: [6730.4675, 7092.7051, 7535.4165, 7000]
    gain: [0.0378, 0.0126, 0.006, 0.05]
    kappa: [0.2248, 0.5768, 0.4182, 0.5]
    lamb: [-2.7516, -1.4897, -4.6377, 0]
    max_gain: 1
    phase: [-83.5843, 44.7818, -108.8384, 0]
    qe: [3.2837, 1.4829, 2.639, 0]
    qi: [34.0135, 7.2, 5.6789, 0]
    readout_length: [11.55, 10.5, 10, 5]
    reps: [1, 4, 1, 1]
    reps_base: 500
    rescale: [false, false, false, false]
    reset: [3, 3, 3, 3]
    rounds: [1, 1, 1, 1]
    rounds_base: 1
    sigma: [1.2893, 1.2111, 1.1366, 0]
    threshold: [3.8709, 0.8867, -0.5359, 10]
    tm: [-0.0164, 0.4755, -0.0172, 0]
    trig_offset: [0.65, 0.65, 0.65, 0.5]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 0, 0, 0]
        type: [dyn, dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [0, 0, 0, 0]
        nyquist: [1, 1, 1, 1]
        type: [full, full, full, full]
      readout:
        ch: [2, 2, 2, 2]
        nyquist: [2, 2, 2, 2]
        type: [full, full, full, full]
