aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [27.83, 1, 50]
    T2e: [20.74, 100, 100]
    T2r: [28.84, 50, 50]
    f_ef: [4468.3782, 3800, 3800]
    f_ge: [4597.6593, 6286.6942, 6000]
    kappa: [0.06, 0.2953, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0231, 0, 0]
    pulses:
      pi_ef:
        gain: [0.1303, 0.15, 0.15]
        phase: [0, 0, 0]
        sigma: [0.02, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
      pi_ge:
        gain: [0.6254, 0.4, 0.15]
        phase: [0, 0, 0]
        sigma: [0.05, 0.1, 0.1]
        sigma_inc: [5, 5, 5]
        type: [gauss, gauss, gauss]
    spec_gain: [1, 1, 1]
    temp: [58.5463, 0, 0]
    tuned_up: [true, false, false]
  readout:
    active_reset: [false, false, false]
    chi: [-1.8254, 0, 0]
    fidelity: [0.4469, 0, 0]
    final_delay: [166.96, 300, 300]
    frequency: [5454.7661, 5979.3295, 6709.0441]
    gain: [1.0, 0.0004, 0.05]
    kappa: [0.4087, 0.7405, 0.6666]
    lamb: [-6.4686, 15.9432, -5.0234]
    max_gain: 1
    phase: [166.5435, 0, 0]
    qe: [1.6642, 2.1812, 1.0315]
    qi: [6.7412, 1.282, 41.3332]
    readout_length: [20.4158, 1, 5]
    reps: [1, 80, 1]
    reps_base: 200
    rescale: [false, false, false]
    reset: [3, 3, 3]
    rounds: [1, 1, 1]
    rounds_base: 1
    sigma: [10.9136, 0, 0]
    threshold: [9.6974, 10, 10]
    tm: [0.6822, 0, 0]
    trig_offset: [0.52, 0.52, 0.52]
hw:
  soc:
    adcs:
      readout:
        attn: [0, 0, 0]
        ch: [0, 0, 0]
        type: [dyn, dyn, dyn]
    dacs:
      qubit:
        attn1: [0, 0, 0]
        attn2: [0, 0, 0]
        ch: [1, 1, 1]
        nyquist: [1, 1, 1]
        type: [full, full, full]
      readout:
        attn1: [0, 0, 0]
        attn2: [0, 0, 0]
        ch: [0, 0, 0]
        nyquist: [2, 2, 2]
        type: [full, full, full]
