aliases: {soc: bf3_soc}
device:
  qubit:
    T1: [103.86, 156.01, 150, 150, 150, 150]
    T2e: [67.7, 37.16, 300, 300, 300, 300]
    T2r: [10.01, 33.03, 150, 150, 150, 150]
    f_ef: [3437.1538, 3800, 3800, 3800, 3800, 3800]
    f_ge: [3585.3158, 3391.5057, 4000, 4000, 4000, 4000]
    kappa: [1.3467, 3.4124, 0, 0, 0, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0096, 0, 0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.0384, 0.15, 0.15, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0, 0, 0]
        sigma: [0.04, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [4, 5, 5, 5, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.0209, 0.0413, 0.15, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0, 0, 0]
        sigma: [0.04, 0.04, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss]
    spec_gain: [1, 0.1, 0.1, 0.1, 0.1, 0.1]
    temp: [37.0571, 0, 0, 0, 0, 0]
    tuned_up: [true, true, false, false, false, false]
  readout:
    active_reset: [true, true, false, false, false, false]
    chi: [-0.2556, 0, 0, 0, 0, 0]
    fidelity: [0.8226, 0.8456, 0, 0, 0, 0]
    final_delay: [623.13, 936.09, 900, 900, 900, 900]
    frequency: [7144.857, 7173.6278, 7000, 7228.5287, 7260.1859, 7000]
    gain: [0.078, 0.09, 0.05, 0.05, 0.05, 0.05]
    kappa: [0.129, 0.2001, 0.5, 0.2125, 0.2062, 0.5]
    lamb: [0.6703, -2.7174, 0, 0, 0, 0]
    max_gain: 1
    phase: [34.7932, 74.9477, 0, 0, 0, 0]
    qe: [11.0376, 8.2052, 0, 5.9616, 4.5509, 0]
    qi: [11.1106, 6.3656, 0, 7.9226, 15.5484, 0]
    readout_length: [15.9279, 9.2143, 5, 5, 5, 5]
    reps: [1.2622, 1, 1, 1, 1, 1]
    reps_base: 150
    rescale: [false, false, false, false, false, false]
    reset_e: [0, 0, 0, 0, 0, 0]
    reset_g: [0, 0, 0, 0, 0, 0]
    rounds: [1, 1, 1, 1, 1, 1]
    rounds_base: 1
    sigma: [0.5035, 0.6959, 0, 0, 0, 0]
    threshold: [2.7659, 3.4911, 10, 10, 10, 10]
    tm: [0.2438, 0.1707, 0, 0, 0, 0]
    trig_offset: [0.4545, 0.65, 0.65, 0.45, 0.45, 0.45]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 0, 0, 0, 0, 0]
        type: [dyn, dyn, dyn, dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1, 1, 1, 1]
        nyquist: [1, 1, 1, 1, 1, 1]
        type: [full, full, full, full, full, full]
      readout:
        ch: [0, 0, 0, 0, 0, 0]
        nyquist: [2, 2, 2, 2, 2, 2]
        type: [full, full, full, full, full, full]
stark:
  f: [45, 45, null, null, null, null]
  fneg: [-35, -30, null, null, null, null]
  l: [11.9827, 8.3771, null, null, null, null]
  lneg: [19.8764, 5.5242, null, null, null, null]
  o: [-0.2146, -0.2632, null, null, null, null]
  oneg: [-0.5938, 0.1761, null, null, null, null]
  q: [270.3144, 102.8626, null, null, null, null]
  qneg: [247.216, 66.5, null, null, null, null]
