aliases: {soc: bf3_soc}
device:
  qubit:
    T1: [101.19, 150, 150, 150, 150, 150]
    T2e: [84.77, 300, 300, 300, 300, 300]
    T2r: [8.62, 150, 150, 150, 150, 150]
    f_ef: [3438.5278, 3800, 3800, 3800, 3800, 3800]
    f_ge: [3584.7707, 4000, 4000, 4000, 4000, 4000]
    kappa: [1.3467, 0, 0, 0, 0, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.2, 0.15, 0.15, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0, 0, 0]
        sigma: [1.36, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [4, 5, 5, 5, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.1653, 0.15, 0.15, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0, 0, 0]
        sigma: [0.06, 0.1, 0.1, 0.1, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4, 5, 5]
        type: [gauss, gauss, gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1, 1, 1]
    temp: [0, 0, 0, 0, 0, 0]
    tuned_up: [true, false, false, false, false, false]
  readout:
    active_reset: [false, false, false, false, false, false]
    chi: [4.2173, 0, 0, 0, 0, 0]
    fidelity: [0.3861, 0, 0, 0, 0, 0]
    final_delay: [607.15, 900, 900, 900, 900, 900]
    frequency: [7144.6826, 7174.3805, 7000, 7246.6119, 7247.044, 7000]
    gain: [0.2592, 0.3, 0.05, 0.05, 0.05, 0.05]
    kappa: [0.1559, 2.9889, 0.5, 98.7024, 10.9174, 0.5]
    lamb: [-0.0446, 0, 0, 0, 0, 0]
    max_gain: 1
    phase: [98.1192, 0, 0, 0, 0, 0]
    qe: [55.5096, 0.2948, 0, 0.0073, 0.0664, 0]
    qi: [4.9962, 1.2865, 0, 8291.1746, 351624.1232, 0]
    readout_length: [34.7288, 5, 5, 5, 5, 5]
    reps: [1, 1, 1, 1, 1, 1]
    reps_base: 250
    rescale: [false, false, false, false, false, false]
    reset_e: [0, 0, 0, 0, 0, 0]
    reset_g: [0, 0, 0, 0, 0, 0]
    rounds: [1, 1, 1, 1, 1, 1]
    rounds_base: 1
    sigma: [0.0362, 0, 0, 0, 0, 0]
    threshold: [0.2751, 10, 10, 10, 10, 10]
    tm: [0.7834, 0, 0, 0, 0, 0]
    trig_offset: [0.65, 0.65, 0.65, 0.45, 0.45, 0.45]
hw:
  soc:
    adcs:
      readout:
        ch: [0, 0, 0, 0, 0, 0]
        type: [dyn, dyn, dyn, dyn, dyn, dyn]
    dacs:
      qubit:
        ch: [1, 1, 1, 1, 1, 1]
        nyquist: [1, 1, 1, 1, 1, 1]
        type: [full, full, full, full, full, full]
      readout:
        ch: [0, 0, 0, 0, 0, 0]
        nyquist: [2, 2, 2, 2, 2, 2]
        type: [full, full, full, full, full, full]
