Delta: [3559.4929, null, null, null, null, null]
Ec: [0.1348, 0.1785, 0.1785, 0.1785, 0.1785, 0.1785]
Ej: [12.8671, 12.2781, 12.2781, 12.2781, 12.2781, 12.2781]
Q1: [null, null, null, null, null, null]
Q1_max: [null, null, null, null, null, null]
Q1_mean: [null, null, null, null, null, null]
Sum: [10729.9625, null, null, null, null, null]
T1_max: [null, null, null, null, null, null]
T1_mean: [null, null, null, null, null, null]
T1_nopurcell: [null, null, null, null, null, null]
T1_purcell: [null, null, null, null, null, null]
T1max_nopurcell: [null, null, null, null, null, null]
T1mean_nopurcell: [null, null, null, null, null, null]
T2E_max: [null, null, null, null, null, null]
T2E_mean: [null, null, null, null, null, null]
T2R_max: [null, null, null, null, null, null]
T2R_mean: [null, null, null, null, null, null]
Tphi: [null, null, null, null, null, null]
alpha: [-148.081, -200, -200, -200, -200, -200]
g_chi: [null, -0.0, -0.0, -0.0, -0.0, -0.0]
g_lamb: [10.9182, null, null, null, null, null]
kappa_low: [null, null, null, null, null, null]
ng: [null, null, null, null, null, null]
nqubits: 6
ratio: [95.4297, 68.7895, 68.7895, 68.7895, 68.7895, 68.7895]
