Delta: [3559.5412, 3174.3805, 3000, 3246.6119, 3247.044, 3000]
Ec: [0.1349, 0.1785, 0.1785, 0.1785, 0.1785, 0.1785]
Ej: [12.8617, 12.2781, 12.2781, 12.2781, 12.2781, 12.2781]
Q1: [1.7686, 3.7699, 3.7699, 3.7699, 3.7699, 3.7699]
Q1_max: [null, null, null, null, null, null]
Q1_mean: [null, null, null, null, null, null]
Sum: [10730.1728, 11174.3805, 11000, 11246.6119, 11247.044, 11000]
T1_max: [null, null, null, null, null, null]
T1_mean: [null, null, null, null, null, null]
T1_nopurcell: [null, null, null, null, null, null]
T1_purcell: [null, null, null, null, null, null]
T1max_nopurcell: [null, null, null, null, null, null]
T1mean_nopurcell: [null, null, null, null, null, null]
T2E_max: [null, null, null, null, null, null]
T2E_mean: [null, null, null, null, null, null]
T2R_max: [null, null, null, null, null, null]
T2R_mean: [null, null, null, null, null, null]
Tphi: [119.0131, .inf, .inf, .inf, .inf, .inf]
alpha: [-148.162, -200, -200, -200, -200, -200]
g_chi: [65.5615, -0.0, -0.0, -0.0, -0.0, -0.0]
g_lamb: [null, 0.0, 0.0, 0.0, 0.0, 0.0]
kappa_low: [null, null, null, null, null, null]
ng: [null, .inf, .inf, .inf, .inf, .inf]
nqubits: 6
ratio: [95.3427, 68.7895, 68.7895, 68.7895, 68.7895, 68.7895]
