aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [22.65]
    T2e: [27.95]
    T2r: [20.97]
    f_ef: [4435.4181]
    f_ge: [1000.0]
    kappa: [0.2166]
    low_gain: 0.003
    max_gain: 1
    pop: [0.0078]
    pulses:
      pi_ef:
        gain: [0.5168]
        phase: [0]
        sigma: [0.0]
        sigma_inc: [4]
        type: [gauss]
      pi_ge:
        gain: [0.4028]
        phase: [0]
        sigma: [0.01]
        sigma_inc: [5]
        type: [gauss]
    spec_gain: [4]
    temp: [48.2978]
    tuned_up: [true]
  readout:
    active_reset: [false]
    chi: [-0.8948]
    fidelity: [0.412]
    final_delay: [135.92]
    frequency: [2760]
    gain: [0.0363]
    kappa: [0.3189]
    lamb: [-2.8611]
    max_gain: 1
    phase: [-167.2488]
    qe: [4.9507]
    qi: [3.6793]
    readout_length: [6.93]
    reps: [1, 4, 10.4211, 1]
    reps_base: 500
    rescale: [false]
    reset: [3]
    rounds: [1]
    rounds_base: 1
    sigma: [1.5187]
    threshold: [-27.417]
    tm: [0.9425]
    trig_offset: [0.55]
hw:
  soc:
    adcs:
      readout:
        ch: [10, 10, 10, 10]
        type: [dyn]
    dacs:
      qubit:
        ch: [1]
        nyquist: [1]
        type: [full]
      readout:
        ch: [0]
        nyquist: [2]
        type: [full]
