aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [0.5, 0.5, 0.68, 50]
    T2e: [100, 0.4, 0.98, 100]
    T2r: [5, 0.07, 0.37, 50]
    f_ef: [5616.9564, 4378.2477, 3264.1232, 3800]
    f_ge: [5663.3785, 4540.6196, 3397.4147, 2558.6069]
    f_ge_max: [5663.3785, 4540.6196, 3471.0461, 2558.6069]
    kappa: [-7.9447, -8.7761, 2.7972, 36.0622]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [1.1486, 0.7002, 0.142, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.025, 0.01, 0.01, 0.1]
        sigma_inc: [4, 3, 3, 4]
        type: [gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.1055, 0.6573, 0.2086, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.015, 0.004, 0.007, 0.1]
        sigma_inc: [4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1]
    sweet_spot_ac: [0.002, 0.002, 0.1512, 0]
    temp: [0, 0, 0, 0]
    tuned_up: [false, true, true, false]
  readout:
    active_reset: [false, false, false, false]
    chi: [-0.4338, -4.1093, -4.7485, 0]
    e_mean: [90.5594, 24.0302, -2.3537, 0]
    fidelity: [0.171, 0.3093, 0.325, 0]
    final_delay: [5.0, 5.0, 5.0, 10]
    frequency: [3939.1858, 7145.1788, 7675.3012, 8289.8727]
    g_mean: [57.8874, 3.4833, -61.0189, 0]
    gain: [0.1, 0.4396, 0.3388, 0.1]
    kappa: [0.7882, 3.8998, 6.7107, 3.2334]
    lamb: [-0.4883, 49.2146, -7.5425, -0.9335]
    max_gain: 1
    phase: [0.1655, -93.1663, 132.1639, 0]
    qe: [0.6726, 0.1997, 0.3509, 0.2781]
    qi: [1.9448, 2.2217, 0.1697, 3.2885]
    readout_length: [0.5082, 0.4607, 1.4246, 1]
    reps: [1, 1, 1, 2]
    reps_base: 1300
    rescale: [false, false, false, false]
    reset: [3, 3, 3, 3]
    rounds: [1, 1, 1, 4]
    rounds_base: 1
    sigma: [71.6083, 24.7597, 31.2093, 0]
    threshold: [88.573, 18.402, -35.5148, 10]
    tm: [5.338, 1.6909, 1.3775, 0]
    trig_offset: [0.52, 0.52, 0.48, 0.5]
hw:
  soc:
    adcs:
      readout:
        attn: [0, 0, 0, 0]
        ch: [0, 0, 0, 0]
        filter_bw: [500, 100, 500, 1000]
        filter_fc: [3939.1391, 7146.7939, 7681.8329, 8289.9904]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        type: [dyn, dyn, dyn, dyn]
    dacs:
      flux:
        ch: [0, 0, 9, 8]
        dc_ch: [0, 0, 3, 0]
        dc_val: [0, 0, 0, 0]
        nyquist: [1, 1, 1, 1]
        quad_a: [0, 0, -3160.4978, 0]
        quad_b: [0, 0, 955.9015, 0]
        quad_c: [0, 0, 3398.7674, 0]
        type: [int, int, int, int]
      qubit:
        attn1: [0, 0, 8, 10]
        attn2: [0, 0, 0, 0]
        ch: [1, 1, 1, 1]
        filter_bw: [200, 100, 100, 1000]
        filter_fc: [5847.1338, 4439.224, 3470, 2558.6069]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        nyquist: [1, 1, 1, 1]
        type: [full, full, full, full]
      readout:
        attn1: [30, 30, 12, 10]
        attn2: [20, 0, 0, 0]
        ch: [0, 0, 0, 0]
        filter_bw: [100, 100, 100, 100]
        filter_fc: [3939.1391, 7146.7939, 7681.8329, 8289.9904]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        nyquist: [2, 2, 2, 2]
        type: [full, full, full, full]
    rfboard_active:
      adc:
        '0': {attn: 0, filter_bw: 500, filter_fc: 7681.8329, filter_type: bandpass,
          qubit: 2}
      dac_qubit:
        '1': {attn1: 8, attn2: 0, filter_bw: 100, filter_fc: 3470, filter_type: bandpass,
          qubit: 2}
      dac_readout:
        '0': {attn1: 12, attn2: 0, filter_bw: 100, filter_fc: 7681.8329, filter_type: bandpass,
          qubit: 2}
