aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [0.5, 0.5, 1, 1]
    T2e: [0.25, 0.25, 1, 1]
    T2r: [0.09, 0.07, 1, 1]
    f_ef: [3800, 3920, 3800, 3800]
    f_ge: [5584.3921, 4081.5057, 3475, 4000]
    kappa: [0, -3.3885, 0, 0]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.15, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.1, 0.005, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.3806, 0.2, 0.5437, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.005, 0.005, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1]
    temp: [0, 0, 0, 0]
    tuned_up: [true, false, false, false]
  readout:
    active_reset: [false, false, false, false]
    chi: [0, -0.274, 0, 0]
    e_mean: [124.8681, 7.677, 0, 0]
    fidelity: [0.1024, 0.0519, 0, 0]
    final_delay: [5.0, 5.0, 10, 10]
    frequency: [3941.5363, 7142.4256, 7687.5948, 8292.735]
    g_mean: [118.2397, 3.0308, 0, 0]
    gain: [0.2673, 0.1414, 0.05, 0.05]
    kappa: [0.7028, 3.2039, 3.1194, 3]
    lamb: [-20.1643, -7.4256, -7.6233, 0]
    max_gain: 1
    nstark: [null, null, null, null]
    phase: [22.3647, -89.6679, 0, 0]
    qe: [1.033, 0.2229, 0.3322, 2.4827]
    qi: [1.2269, 53973376.5921, 0.9541, 0.6789]
    readout_length: [0.81, 0.0546, 1, 1]
    reps: [1, 2, 6, 6]
    reps_base: 1000
    rescale: [false, false, false, false]
    reset: [3, 3, 3, 3]
    rounds: [1, 1, 1, 3]
    rounds_base: 1
    sigma: [50.1425, 34.222, 0, 0]
    threshold: [140.9651, -0.3197, 10, 10]
    tm: [3.8063, 0.7787, 0, 0]
    trig_offset: [0.5, 0.43, 0.5, 0.5]
hw:
  soc:
    adcs:
      readout:
        attn: [30, 0, 0, 0]
        ch: [10, 10, 10, 10]
        filter_bw: [100, 100, 200, 100]
        filter_fc: [3956.6412, 7124.9177, 7690.6064, 8250.3706]
        filter_type: [bypass, bandpass, bypass, bypass]
        type: [dyn, dyn, dyn, dyn]
    dacs:
      qubit:
        attn1: [0, 10, 0, 0]
        attn2: [0, 0, 0, 0]
        ch: [2, 2, 2, 2]
        filter_bw: [1000, 1000, 1000, 1000]
        filter_fc: [5500, 4080, 3500, 2500]
        filter_type: [bandpass, bandpass, bypass, bypass]
        nyquist: [1, 1, 1, 1]
        type: [full, full, full, full]
      readout:
        attn1: [30, 15, 20, 0]
        attn2: [10, 0, 0, 0]
        ch: [3, 3, 3, 3]
        filter_bw: [100, 100, 100, 100]
        filter_fc: [3956.6412, 7124.9177, 7690.6064, 8250.3706]
        filter_type: [bandpass, bandpass, bypass, bypass]
        nyquist: [2, 2, 2, 2]
        type: [full, full, full, full]
    rfboard_active:
      adc:
        '0': {attn: 0, filter_bw: 1000, filter_fc: 0, filter_type: bypass, qubit: 2}
        '10': {attn: 0, filter_bw: 100, filter_fc: 8250.3706, filter_type: bypass,
          qubit: 3}
        '4': {attn: 10, filter_bw: 1000, filter_fc: 0, filter_type: bypass, qubit: 0}
      dac_qubit:
        '1': {attn1: 0, attn2: 0, filter_bw: 1000, filter_fc: 0, filter_type: bypass,
          qubit: 3}
        '2': {attn1: 0, attn2: 0, filter_bw: 1000, filter_fc: 2500, filter_type: bypass,
          qubit: 3}
      dac_readout:
        '0': {attn1: 0, attn2: 0, filter_bw: 1000, filter_fc: 0, filter_type: bypass,
          qubit: 2}
        '2': {attn1: 0, attn2: 0, filter_bw: 1000, filter_fc: 0, filter_type: bypass,
          qubit: 0}
        '3': {attn1: 0, attn2: 0, filter_bw: 100, filter_fc: 8250.3706, filter_type: bypass,
          qubit: 3}
