aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [50, 1.08, 1.41, 50]
    T2e: [100, 1.5, 1.68, 100]
    T2r: [50, 1.5, 1.5, 50]
    f_ef: [3800, 4332.8232, 3800, 3800]
    f_ge: [5347.1338, 4550.3308, 3430, 7058.6069]
    kappa: [1.3087, 9.6454, -2.8192, 36.0622]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [0.0245, 0.15, 0.15, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.1, 0.5, 0.1, 0.1]
        sigma_inc: [4, 4, 4, 4]
        type: [gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.15, 0.2634, 0.2141, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.1, 0.007, 0.01, 0.1]
        sigma_inc: [4, 3, 3, 4]
        type: [gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1]
    temp: [0, 0, 0, 0]
    tuned_up: [false, true, false, false]
  readout:
    active_reset: [false, false, false, false]
    chi: [0, -4.1093, -1.3698, 0]
    fidelity: [0, 0.2797, 0.032, 0]
    final_delay: [300, 10, 10, 300]
    frequency: [3939.1391, 7146.5452, 7681.8329, 8289.9904]
    gain: [0.1, 0.4618, 0.3, 0.1]
    kappa: [0.4812, 3.9684, 3.2852, 2.9495]
    lamb: [13.8637, 49.2146, -8.1959, -1.4064]
    max_gain: 1
    phase: [0, 48.7789, 32.0662, 0]
    qe: [0.9178, 0.1991, 0.2763, 0.3479]
    qi: [7.5672, 1.8902, 1.5223, 1.4623]
    readout_length: [5, 1.2248, 1.701, 5]
    reps: [1, 4, 5, 1]
    reps_base: 250
    rescale: [false, false, false, false]
    reset: [3, 3, 3, 3]
    rounds: [1, 1, 1, 1]
    rounds_base: 1
    sigma: [0, 16.8023, 22.8504, 0]
    threshold: [10, 21.0395, -2.631, 10]
    tm: [0, 1.7597, 0.2361, 0]
    trig_offset: [0.52, 0.52, 0.52, 0.5]
hw:
  soc:
    adcs:
      readout:
        attn: [0, 0, 0, 0]
        ch: [0, 0, 0, 0]
        type: [dyn, dyn, dyn, dyn]
    dacs:
      qubit:
        attn1: [0, 0, 0, 0]
        attn2: [0, 0, 0, 0]
        ch: [1, 1, 1, 1]
        nyquist: [1, 1, 1, 1]
        type: [full, full, full, full]
      readout:
        attn1: [0, 0, 0, 0]
        attn2: [0, 0, 0, 0]
        ch: [0, 0, 0, 0]
        nyquist: [2, 2, 2, 2]
        type: [full, full, full, full]
