Delta: [-1407.9947, 2600.5699, 4251.8329, 1231.3835]
Ec: [0.6471, 0.1358, 0.0029, 1.0537]
Ej: [7.0343, 20.2114, 480.0263, 7.664]
Q1: [1.6799, 0.0143, 0.0304, 2.2175]
Sum: [9286.2729, 11693.0179, 11111.8329, 15348.5973]
T1_nopurcell: [null, null, null, null]
T1_purcell: [null, null, null, null]
Tphi: [.inf, .inf, 4.1558, .inf]
alpha: [-1547.1338, -146.0702, 370, -3258.6069]
g: [chi, chi, chi, chi]
g_chi: [-0.0, 318.8564, null, -0.0]
g_lamb: [151.6859, null, 158.7566, 40.0399]
kappa_low: [null, null, null, null]
ng: [null, 16.6298, null, null]
nqubits: 4
nreadout: [null, null, null, null]
ratio: [10.8698, 148.8056, 167501.7743, 7.2731]
stats:
  q1_max: [null, null, null, null]
  q1_mean: [null, null, null, null]
  q1_std: [null, null, null, null]
  t1_max: [null, null, null, null]
  t1_mean: [null, null, null, null]
  t1_std: [null, null, null, null]
  t1max_nopurcell: [null, null, null, null]
  t1mean_nopurcell: [null, null, null, null]
  t2e_max: [null, null, null, null]
  t2e_mean: [null, null, null, null]
  t2e_std: [null, null, null, null]
  t2r_max: [null, null, null, null]
  t2r_mean: [null, null, null, null]
  t2r_std: [null, null, null, null]
  tphi_max: [null, null, null, null]
  tphi_mean: [null, null, null, null]
  tphi_std: [null, null, null, null]
