Delta: [-51.7989, 4469.4749, 2124.1958, 4358.307]
Ec: [0.1785, 0.1372, 0.1371, 0.1785]
Ej: [12.2781, 10.2743, 24.4275, 12.2781]
Q1: [0.0251, 0.0267, 0.0253, 0.0251]
Sum: [7948.2011, 10899.2661, 12195.078, 12358.307]
T1_nopurcell: [null, null, null, null]
T1_purcell: [null, null, null, null]
Tphi: [.inf, 0.2164, .inf, .inf]
alpha: [-200, -152.8956, -146.4411, -200]
g: [chi, chi, chi, chi]
g_chi: [-0.0, 0.0, 88.4892, -0.0]
g_lamb: [-0.0, 130.5648, 239.4315, null]
kappa_low: [null, null, null, null]
ng: [null, 6412.9037, 144.0617, null]
nqubits: 4
nreadout: [null, null, null, null]
ratio: [68.7895, 74.8713, 178.1477, 68.7895]
stats:
  q1_max: [null, null, null, null]
  q1_mean: [null, null, null, null]
  q1_std: [null, null, null, null]
  t1_max: [null, null, null, null]
  t1_mean: [null, null, null, null]
  t1_std: [null, null, null, null]
  t1max_nopurcell: [null, null, null, null]
  t1mean_nopurcell: [null, null, null, null]
  t2e_max: [null, null, null, null]
  t2e_mean: [null, null, null, null]
  t2e_std: [null, null, null, null]
  t2r_max: [null, null, null, null]
  t2r_mean: [null, null, null, null]
  t2r_std: [null, null, null, null]
  tphi_max: [null, null, null, null]
  tphi_mean: [null, null, null, null]
  tphi_std: [null, null, null, null]
