aliases: {ip: 10.108.30.23, soc: bf1_soc}
device:
  qubit:
    T1: [1, 1, 0.56, 50]
    T2e: [100, 1.5, 1.12, 100]
    T2r: [1.5, 1.5, 1.5, 50]
    f_ef: [5616.9564, 4378.2477, 3264.1232, 3800]
    f_ge: [5618.1597, 4545.5226, 3396.9825, 2558.6069]
    kappa: [-7.9447, -8.7761, -2.4128, 36.0622]
    low_gain: 0.003
    max_gain: 1
    pop: [0, 0, 0, 0]
    pulses:
      pi_ef:
        gain: [1.1486, 0.7002, 0.142, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.025, 0.01, 0.01, 0.1]
        sigma_inc: [4, 3, 3, 4]
        type: [gauss, gauss, gauss, gauss]
      pi_ge:
        gain: [0.2, 0.372, 0.0391, 0.15]
        phase: [0, 0, 0, 0]
        sigma: [0.015, 0.01, 0.007, 0.1]
        sigma_inc: [4, 3, 4, 4]
        type: [gauss, gauss, gauss, gauss]
    spec_gain: [1, 1, 1, 1]
    temp: [0, 0, 0, 0]
    tuned_up: [true, true, true, false]
  readout:
    active_reset: [false, false, false, false]
    chi: [-0.4338, -4.1093, -4.7485, 0]
    fidelity: [0.1095, 0.277, 0.1621, 0]
    final_delay: [10, 10, 5.0, 10]
    frequency: [3938.8099, 7143.8095, 7680.7729, 8289.8727]
    gain: [0.7188, 0.5171, 0.1383, 0.1]
    kappa: [0.7635, 3.4394, 5.8074, 3.2334]
    lamb: [-0.4883, 49.2146, -7.5425, -0.9335]
    max_gain: 1
    phase: [-65.3982, 116.5504, -64.6126, 0]
    qe: [0.7429, 0.2451, 0.2484, 0.2781]
    qi: [1.6882, 1.3625, 0.283, 3.2885]
    readout_length: [0.5293, 0.9599, 2.3687, 1]
    reps: [1, 1, 1, 2]
    reps_base: 1000
    rescale: [false, false, false, false]
    reset: [3, 3, 3, 3]
    rounds: [1, 1, 1, 4]
    rounds_base: 1
    sigma: [71.1929, 20.9258, 23.1457, 0]
    threshold: [40.5336, 32.3762, 9.3565, 10]
    tm: [5.7326, 2.9299, 2.0245, 0]
    trig_offset: [0.52, 0.52, 0.52, 0.5]
hw:
  soc:
    adcs:
      readout:
        attn: [0, 0, 0, 0]
        ch: [0, 0, 0, 0]
        filter_bw: [500, 100, 500, 1000]
        filter_fc: [3939.1391, 7146.7939, 7681.8329, 8289.9904]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        type: [dyn, dyn, dyn, dyn]
    dacs:
      flux:
        ch: [0, 0, 9, 8]
        nyquist: [1, 1, 1, 1]
        type: [int, int, int, int]
      qubit:
        attn1: [0, 5, 0, 10]
        attn2: [0, 0, 0, 0]
        ch: [1, 1, 1, 1]
        filter_bw: [500, 100, 1000, 1000]
        filter_fc: [5847.1338, 4439.224, 3430, 2558.6069]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        nyquist: [1, 1, 1, 1]
        type: [full, full, full, full]
      readout:
        attn1: [30, 30, 12, 10]
        attn2: [20, 0, 0, 0]
        ch: [0, 0, 0, 0]
        filter_bw: [100, 100, 100, 100]
        filter_fc: [3939.1391, 7146.7939, 7681.8329, 8289.9904]
        filter_type: [bandpass, bandpass, bandpass, bandpass]
        nyquist: [2, 2, 2, 2]
        type: [full, full, full, full]
    rfboard_active:
      adc:
        '0': {attn: 0, filter_bw: 500, filter_fc: 7681.8329, filter_type: bandpass,
          qubit: 2}
      dac_qubit:
        '1': {attn1: 0, attn2: 0, filter_bw: 1000, filter_fc: 3430, filter_type: bandpass,
          qubit: 2}
      dac_readout:
        '0': {attn1: 12, attn2: 0, filter_bw: 100, filter_fc: 7681.8329, filter_type: bandpass,
          qubit: 2}
